let
    NewYorkPeople = AnalysisServices.Database(RandomServer, RandomDatabase, [Query="EVALUATE#(lf)VAR TheGreatGatsbySSN = 250000#(lf)VAR NewYorkPeople =#(lf)    FILTER (#(lf)        'New York People',#(lf)        // The FILTER function does create a row context. You can therefore refer to the current SSN.#(lf)        // Because there is a row context, there is no filter context.#(lf)        NOT ( 'New York People'[SSN] = TheGreatGatsbySSN )#(lf)    )#(lf)VAR TheGreatGatsbyRow =#(lf)    ROW (#(lf)            ""SSN"", TheGreatGatsbySSN,#(lf)            ""Gender"", ""Male"",#(lf)            ""Group"", ""Gangster"",#(lf)#(tab)#(tab)#(tab)""AreaCode"", ""AAA-3"",#(lf)            ""Maximum Cups Per Day"", 9,#(lf)            ""Ethnicity"", ""White"",#(lf)#(lf)            ""Speakeasy Membership Start Date"", DATE ( 1921, 3, 4 ),#(lf)            ""Speakeasy Membership End Date"", DATE ( 1923, 5, 3 ),#(lf)       // The ROW function does not operate within a row context. For example this is not possible#(lf)       //  ,""Membership Duration (days)"", [Membership End Date] - [Membership Start Date]#(lf)#(tab)   #(lf)#(tab)        ""Is Speakeasy Visitor"", ""Is Speakeasy Visitor""#(lf)    )#(lf)RETURN#(lf)    UNION ( NewYorkPeople, TheGreatGatsbyRow )", Implementation="2.0"]),
    #"Renamed Columns" = Table.RenameColumns(NewYorkPeople,{{"New York People[SSN]", "SSN"}, {"New York People[Gender]", "Gender"}, {"New York People[Group]", "Group"}, {"New York People[Area Code]", "Area Code"},  {"New York People[Maximum Cups Per Day]", "Maximum Cups Per Day"}, {"New York People[Ethnicity]", "Ethnicity"}, {"New York People[Is Speakeasy Visitor]", "Is Speakeasy Visitor"}, {"New York People[Speakeasy Membership Start Date]", "Speakeasy Membership Start Date"}, {"New York People[Speakeasy Membership End Date]", "Speakeasy Membership End Date"}})
in
    #"Renamed Columns"